name: Conty CI

on:
  schedule:
    - cron:  '0 0 * * 5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          chmod +x create-conty.sh
          ./create-conty.sh
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Conty
          path: build/conty.sh
