name: Conty AutoRelease CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Conty
        run: |
          chmod +x create-conty.sh
          ./create-conty.sh
      - uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
         tag_name: continuous
         github_token: ${{ secrets.GITHUB_TOKEN }}
         delete_release: true

      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "continuous"

      - uses: softprops/action-gh-release@v1
        with:
          files: ./build/conty.sh
          prerelease: true
          draft: false
          tag_name: continuous
          name: Continuous build
